/**
 * Cross-language proof: this kernel must hash payloads identically to the
 * Python kernel, or two services keyed the same way would fail to deduplicate
 * each other's work.
 *
 * The vectors in `vectors/python-jcs-vectors.json` are GENERATED BY THE PYTHON
 * IMPLEMENTATION (see generate-from-python.py), not written by hand. Hand-written
 * expectations would only prove this file agrees with itself.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { payloadHashHex, canonicalBytes, CanonicalizationError } from "../src/canonical.ts";

const here = dirname(fileURLToPath(import.meta.url));
const vectors: Array<{ payload: unknown; hash: string }> = JSON.parse(
  readFileSync(join(here, "vectors/python-jcs-vectors.json"), "utf8"),
);

test("every payload hashes identically to the Python kernel", () => {
  assert.ok(vectors.length >= 15, "vector suite should not silently shrink");
  for (const v of vectors) {
    assert.equal(
      payloadHashHex(v.payload),
      v.hash,
      `hash diverged from Python for ${JSON.stringify(v.payload)?.slice(0, 80)}`,
    );
  }
});

test("object key order does not change the hash", () => {
  assert.equal(payloadHashHex({ a: 1, b: 2 }), payloadHashHex({ b: 2, a: 1 }));
});

test("array order DOES change the hash — order is data", () => {
  assert.notEqual(payloadHashHex([1, 2]), payloadHashHex([2, 1]));
});

test("-0 and 0 canonicalize the same, per JCS", () => {
  assert.equal(canonicalBytes(-0).toString(), "0");
});

test("values JSON cannot represent are rejected, never coerced", () => {
  // Each of these would otherwise let two different payloads produce one hash:
  // JSON.stringify turns NaN/Infinity into null, drops undefined members, and
  // calls Date.toJSON(). Silent coercion is how a dedupe key stops being unique.
  for (const bad of [NaN, Infinity, -Infinity, undefined, new Date(0), 10n, new Map(), new Set()]) {
    assert.throws(() => payloadHashHex(bad), CanonicalizationError, `should reject ${String(bad)}`);
  }
});

test("nested unrepresentable values are caught, with a path", () => {
  try {
    payloadHashHex({ order: { items: [{ qty: NaN }] } });
    assert.fail("should have thrown");
  } catch (e) {
    assert.ok(e instanceof CanonicalizationError);
    assert.match(e.message, /\$\.order\.items\[0\]\.qty/, "error should name the offending path");
  }
});
